### ISSUE TITLE
Buttons in dialogs have rendering issues (PyCharm/IntelliJ IDEA on Windows)

### ISSUE THREAD

**Issue by fib** [phocus/jetbrains#2]
All buttons in dialogs in PyCharm, on Windows, seem to have some sort of rendering issues when you hover over them. However, you can get them to reset by resizing the dialog window. See attached video:

https://user-images.githubusercontent.com/47277578/106812752-17e7ba00-663e-11eb-8924-ca9022c2bb19.mp4

I've tested IntelliJ IDEA as well and pretty much the same thing happens, except you have to click the button (hovering doesn't trigger the same issue). I'm not sure if Windows (I'm assuming this is Windows-specific, I didn't test on Linux but I'm assuming this would've been fixed already if the issue existed there as well) is something you're planning to support, but thought it'd be worth opening an issue for anyway.

I really like the theme and while this isn't necessarily something that severely impacts functionality it's somewhat annoying when I'm unsure of what the buttons say, as sometimes it becomes unreadable after only hovering over the button once.

**Comment by yairp03** [comment]
Happened to me too. Would be nice if the problem is fixed.

**Comment by phisch** [comment]
Thanks for the report, i'll look into it and fix it with the next release!

**Comment by fib** [comment]
Glad to hear that!

I kept playing around with it for a bit and I've found that the same behavior occurs in the Replace menu as well (PyCharm): 

![image](https://user-images.githubusercontent.com/47277578/106937324-9cdcdd00-66eb-11eb-8c69-b452de84756e.png)

Additionally, it seems that checkboxes are affected by this issue too, but for some reason not all of them: 

https://user-images.githubusercontent.com/47277578/106937691-107eea00-66ec-11eb-915b-ed1138e45b59.mp4

This is in the Run/Debug menu in PyCharm.

Overall this issue seems weirdly inconsistent, so I thought I'd add this info to hopefully help pinpoint the issue. Also, I'd be more than happy to help with testing this out if needed, so let me know if there's anything specific you'd like me to try.

**Comment by phisch** [comment]
If i recall correctly, there are multiple checkbox and button implementations used throughout intellij products (I really hope they clean their mess up someday and simplify their interface components). I'll have to check what exactly the problem is though. Those problems are expected when creating a theme from scratch, it'll get better over time.

And the theme will hopefully be published as an official plugin in the future, so it updates automatically.
